# render.yaml - Blueprint for your FastAPI API
services:
  - type: web
    name: course-recommendation-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Amazin_db:%40mazin0N@cluster0.nr8aakt.mongodb.net/Course_Recommendation_System?retryWrites=true&w=majority"
